# Sub Assistant
ASSIGN_SUB_ASSISTANT_PROMPT = """
Delegate a task to a sub-assistant

## Args
- agent_identity (str): Sub-agent's name and role in format `name[role]`, e.g: `Alice[Coder]`
- system_prompt (str): System prompt that used to define Sub-agent's characteristics
- task_description (str): The final objective of the task
- instruction (str): Detailed instructions for the sub-agent

## Returns
- str: task id

## Note
- This tool creates a sub-agent with the same capabilities as you (include callable tools, available skills and so on)
- The sub-agent will autonomously work to complete the task
- Once the task is assigned, this tool returns immediately

## When to Use
Use this tool when:
1. The task may take a long time to complete
2. The user explicitly asks you to assign some work to another assistant
3. You are continuing a previous conversation with the sub-assistant (Use the same `agent_identity` in this case)
Typical scenarios:
1. Background processing
2. Delegating complex or time-consuming work

## When NOT to Use
Do NOT use this tool when:
1. The task is simple and can be completed directly
2. The user explicitly asks you to handle the task yourself
3. The task depends heavily on your current reasoning context

## Important Guidelines
How to Write the Task:  
task_description:
Provide a concise description of the task's final goal. This description is visible to you and the user, but not to the sub-agent
- After assigning the task → add this description to your TODO list and mark TODO as **in progress**
- When the task is compeleted → mark TODO as **completed**  
instruction:
The detailed instructions for the sub-agent
It should include:  
- A detailed task goal
- task context
- workspace directory (create one if directory is not exist on disk)
- relevant information
- constraints (list clearly)
- expected output format (if any)  
The instruction must be self-contained because the sub-agent does not have access to your conversation history or reasoning content
Do not reference previous messages such as "above", "earlier", or "previous analysis"
"""

QUERY_SUB_ASSISTANT_PROMPT = """
Query the status, result, and logs of a previously assigned task

## Args
- task_ids (list[str]): The identifier of those tasks you want to query. Query all if empty

## Returns
- dict: Task status information in the following dictionary format:
{
    "task_id": str, # Unique identifier of the task
    "agent_identity": str, # sub-agent's name and role for this task
    "final_goal": str, # Original goal/objective of the task
    "current_todo_list": list, # Optional: Current to-do list maintained by the sub-agent
    "duration": int # Total task execution time in seconds
    "status": str # Task running state
    "outputs": str # The text content generated by the sub-agent
    "errors": str # The error message generated by the task-system
}

## Note
- This tool retrieves the current progress or final result of a task
- that was created using the task delegation tool `assign_sub_assistant`
- The task may still be running, so the result may not be available yet
- If you notice that all todos in current_todo_list are completed, but the task status still shows as `in_progress`, that means the sub-agent is generating the final response. Please continue waiting before completed

## When to Use
Use this tool when:
1. You want to check the progress of a previously assigned task
2. You need to retrieve the result of a task that may have finished
3. The user explicitly asks about the status of a delegated task
4. You forgot a task ID and need to retrieve it again (Use empty task_ids in this case)

## When NOT to Use
Do NOT use this tool when:
1. The task was not created by the delegation tool
2. You already have the result of the task
3. The task was just assigned
"""

STOP_SUB_ASSISTANT_PROMPT = """
Stop one or more previously assigned tasks

## Args
- task_ids (list[str]): The identifier of those tasks you want to stop
- reason (str): Why you are trying to stop those task

## Returns
- dict: Task stop result information in the following dictionary format:
{
    "task_id": str, # Unique identifier of the task
    "status": str, # Updated task state after the stop request
    "message": str # Additional information about the stop operation
}

## Note
- This tool requests the task system to terminate running tasks that were created using the task delegation tool `assign_sub_assistant`
- If a task is currently pending or in_progress, it will be canceled as soon as possible after this tool being called
- If the task has already completed or failed, the stop request will have no effect
- Stopping a task does not guarantee immediate termination
- The task system will attempt to stop the task gracefully

## When to Use
Use this tool when:
1. The user explicitly asks you to cancel a delegated task
2. The delegated task is no longer needed
3. The task is running incorrectly or producing unwanted results
4. A newer task has replaced the old one  
Typical scenarios:
1. The new task already includes the content or objective of the previous task
2. The task has been running for a long time without producing any output
3. The user no longer needs the result of the task

## When NOT to Use
Do NOT use this tool when:
1. The task has already completed or failed
2. You only want to check the progress of a task (use `query_task_by_id` instead)
3. The task status is `in_progress` and outputs or current_todo_list is generated
"""



SCHEDULE_CRON_TASK_PROMPT = """
Delegate a task to a sub-assistant

## Args
- agent_identity (str): Sub-agent's name and role in format `name[role]`, e.g: `Alice[Coder]`
- system_prompt (str): System prompt that used to define Sub-agent's characteristics
- task_description (str): The final objective of the task
- instruction (str): Detailed instructions for the sub-agent

## Returns
- str: task id

## Note
- This tool creates a sub-agent with the same capabilities as you (include callable tools, available skills and so on)
- The sub-agent will autonomously work to complete the task
- Once the task is assigned, this tool returns immediately

## When to Use
Use this tool when:
1. The task may take a long time to complete
2. The user explicitly asks you to assign some work to another assistant
3. You are continuing a previous conversation with the sub-assistant (Use the same `agent_identity` in this case)
Typical scenarios:
1. Background processing
2. Delegating complex or time-consuming work

## When NOT to Use
Do NOT use this tool when:
1. The task is simple and can be completed directly
2. The user explicitly asks you to handle the task yourself
3. The task depends heavily on your current reasoning context

## Important Guidelines
How to Write the Task:  
task_description:
Provide a concise description of the task's final goal. This description is visible to you and the user, but not to the sub-agent
- After assigning the task → add this description to your TODO list and mark TODO as **in progress**
- When the task is compeleted → mark TODO as **completed**  
instruction:
The detailed instructions for the sub-agent
It should include:  
- A detailed task goal
- task context
- workspace directory (create one if directory is not exist on disk)
- relevant information
- constraints (list clearly)
- expected output format (if any)  
The instruction must be self-contained because the sub-agent does not have access to your conversation history or reasoning content
Do not reference previous messages such as "above", "earlier", or "previous analysis"
"""



# OCR
OCR_ANALYSIS_PROMPT = """
Analyze one or more image files and return the recognized text or image analysis result

## Args
- prompt (str): A prompt describing what should be analyzed. This parameter will be ignored when EasyOCR is used
- file_path (str | list[str]): File path / URL of a single image, or a list of image paths / URLs

## Returns
- str: The OCR result produced by EasyOCR or the image analysis result produced by a vision sub-model

## Note:
- This tool internally chooses to use EasyOCR or a vision sub-model
- EasyOCR is used for text recognition only
- A vision sub-model can return recognized text, image description, or other analysis results
- The prompt parameter is only effective when a vision sub-model is used

## When to Use This Tool
Use this tool in these scenarios:
1. When the user wants to understand the content of one or more images
2. When the task requires reading or interpreting images
3. When images need to be described for reasoning purposes
4. When downstream processing depends on textual or visual information from images

## When NOT to Use This Tool
Do NOT use this tool when:
1. The file is not a supported image
2. The task can be solved without viewing the image

## Important Guidelines
- Supported file type: {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
- Maximum number of input images at a time: 5
- Ensure the file path or URL is valid before calling this tool
- Provide a clear prompt when image understanding or structured analysis is needed
- If structured output is required, explicitly specify the expected format
- Do not assume the content of an image without analysis
"""

SEND_IMAGE_PROMPT = """
Send one or more image files to user

## Args
- file_path (str | list[str]): File path / URL of a single image, or a list of image paths / URLs

## Returns
- str: Image send results

## Important Guidelines
- Supported file type: {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
- Maximum number of input images at a time: 5
"""



# File opration
FETCH_FILE_PROMPT = """
Download user uploaded file(s) into sandbox workspace

## Args
- file_ids (str | list[str]): The file's id provided by system

## Returns
- str: File download results

## Note
- Fetched files will be stored in path: `/workspace/user_uploaded/`

## When to Use This Tool
Use this tool in these scenarios:
1. When the user explicitly asks to read, analyze, inspect, or process a previously uploaded file
2. When the file user uploaded is necessary before continuing the task
3. When the file must exist inside the sandbox workspace for execution

## When NOT to Use This Tool
Do NOT use this tool when:
1. You do not have a valid file ID provided by the system
2. The task can be completed without accessing the file
3. User has not uploaded any file or the file is irrelevant to the current task
4. You want to download a file from the internet

## Important Guidelines
- Only download files that are necessary for the current objective
- Avoid redundant downloads of the same file
"""

READ_WORKSPACE_FILE_PROMPT = """
Read a text file inside sandbox workspace

## Args
- file_path (str): File path inside workspace
- start_line (int): 1-based inclusive start line. Use 0 to start from the beginning of the file
- end_line (int): 1-based inclusive end line. Use 0 to read until the end of the file

## Returns
- str: File content with line index

## Note
- Content format this tool return: [line_count_prefix] line_content
- [line_count_prefix] is not the content of the file
"""

WRITE_WORKSPACE_FILE_PROMPT = """
Create a new file or rewrite a exist file inside sandbox workspace

## Args
- file_path (str): File path inside workspace
- content (str): File content
- exist_ok (bool): Overwrite entire file if the file is already exists

## Returns
- str: Success or error message

## Note
- If the file already exists and exist_ok is False, this tool will return an error message and do nothing

## Important Guidelines
- If you just want to create a new file, ensure the value of `exist_ok` is False
- If you want to overwrite an existing file with new content, ensure the value of `exist_ok` is True
"""

DELETE_WORKSPACE_FILE_PROMPT = """
Delete a file or directory inside sandbox workspace

## Args
- file_path (str): File or directory path inside container workspace

## Returns
- str: Success or error message
"""

MOVE_WORKSPACE_FILE_PROMPT = """
Move or copy a file or directory inside sandbox workspace

## Args
- source_path (str): Source file path inside container workspace
- target_path (str): Target file path inside container workspace
- delete_source (bool): Whether to remove the source file after the operation

## Returns
- str: Success or error message

## Note
- If the source file is undeletable, the operation will behave like a copy even

## Important Guidelines
- If you want to copy a file or directory to target_path, ensure the value of `delete_source` is False
- Else if you want to move, keep the value of `delete_source` is True
"""

LIST_WORKSPACE_FILES_PROMPT = """
List files and directories inside workspace.

## Args
- path (str): Sub directory inside workspace, make sure the path start with '/workspace' (None means the workspace root)
- recursively_scan (bool): Whether to recursively scan subdirectories (None means false)

## Returns
- str: A tree-formatted string listing of files and folders

## Note
- The result is limited to a maximum of 500 items and a depth of 6 levels
"""



# Skills
LOAD_SKILL_PROMPT = """
Load the guide for one or more skill

## Args
- name (str | list[str]): The name or name list of the skill(s) to load

## Returns
- str: The skill load result

## Note
- Skills provide reusable capabilities that help you accomplish tasks
- Each skill contains documentation (SKILL.md) that explains:
    - how to use it
    - what commands or tools it provides
    - usage examples
- Loaded skill will be store into the sandbox with path: `/workspace/SKILL/{skill_name}`

## When to Use This Tool
Use this tool in these scenarios:
1. the user's task clearly requires the capability provided by that skill
2. you need more detailed instructions to proceed

## When NOT to Use This Tool
Do NOT use this tool when:
1. skill package has already exists in workspace
2. you do not need a skill to compelete current task

## Important Guidelines
- Avoid loading skills unnecessarily, as this may waste time and resources
- This tool will automatically inject a system message to show the content of SKILL.md
"""



# Memory
WRITE_TODOS_PROMPT = """
Use this tool to create and manage a structured task list for your current work session. This helps you track progress, organize complex tasks, and demonstrate thoroughness to the user.

Only use this tool if you think it will be helpful in staying organized. If the user's request is trivial and takes less than 3 steps, it is better to NOT use this tool and just do the task directly.

## When to Use This Tool
Use this tool in these scenarios:

1. Complex multi-step tasks - When a task requires 3 or more distinct steps or actions
2. Non-trivial and complex tasks - Tasks that require careful planning or multiple operations
3. User explicitly requests todo list - When the user directly asks you to use the todo list
4. User provides multiple tasks - When users provide a list of things to be done (numbered or comma-separated)
5. The plan may need future revisions or updates based on results from the first few steps

## How to Use This Tool
1. When you start working on a task - Mark it as in_progress BEFORE beginning work.
2. After completing a task - Mark it as completed and add any new follow-up tasks discovered during implementation.
3. You can also update future tasks, such as deleting them if they are no longer necessary, or adding new tasks that are necessary. Don't change previously completed tasks.
4. You can make several updates to the todo list at once. For example, when you complete a task, you can mark the next task you need to start as in_progress.

## When NOT to Use This Tool
It is important to skip using this tool when:
1. There is only a single, straightforward task
2. The task is trivial and tracking it provides no benefit
3. The task can be completed in less than 3 trivial steps
4. The task is purely conversational or informational

## Task States and Management

1. **Task States**: Use these states to track progress:
   - pending: Task not yet started
   - in_progress: Currently working on (you can have multiple tasks in_progress at a time if they are not related to each other and can be run in parallel)
   - completed: Task finished successfully

2. **Task Management**:
   - Update task status in real-time as you work
   - Mark tasks complete IMMEDIATELY after finishing (don't batch completions)
   - Complete current tasks before starting new ones
   - Remove tasks that are no longer relevant from the list entirely
   - IMPORTANT: When you write this todo list, you should mark your first task (or tasks) as in_progress immediately!.
   - IMPORTANT: Unless all tasks are completed, you should always have at least one task in_progress to show the user that you are working on something.

3. **Task Completion Requirements**:
   - ONLY mark a task as completed when you have FULLY accomplished it
   - If you encounter errors, blockers, or cannot finish, keep the task as in_progress
   - When blocked, create a new task describing what needs to be resolved
   - Never mark a task as completed if:
     - There are unresolved issues or errors
     - Work is partial or incomplete
     - You encountered blockers that prevent completion
     - You couldn't find necessary resources or dependencies
     - Quality standards haven't been met

4. **Task Breakdown**:
   - Create specific, actionable items
   - Break complex tasks into smaller, manageable steps
   - Use clear, descriptive task names

Being proactive with task management demonstrates attentiveness and ensures you complete all requirements successfully
Remember: If you only need to make a few tool calls to complete a task, and it is clear what you need to do, it is better to just do the task directly and NOT call this tool at all.
""" # From lang chain noqa: E501

UPDATE_MEMORY_PROMPT = """
Write / overwrite / delete a memory

## Args
- memories (list[Memory]): List of memory operations to perform in batch.
    Each memory item must contain:
    - title (str): Memory title, must not be empty.
    - abstract (Optional[str]): Brief summary of the memory.
    - content (str): Memory content. If empty or only whitespace, the memory will be deleted. Otherwise, the memory will be created or updated.

## Returns
- str: Current available memory titles

## Note
- Use this tool to record your important decisions, observations, conclusions or other important information during the current work session
- This tool helps you record previous information so that you can review them later if you forget

## When to Use This Tool
Use this tool in these scenarios:
1. When you are making an important decision
2. When defining constraints, rules, or policies that must be remembered
3. When you make a tool call, the summary or conclusion of the call result that must be remembered
4. When summarizing a important conclusion or observations that must be remembered
5. When you observe that a memo in your memory is outdated and should be deleted (Use a same title and empty content for delete)

## When NOT to Use This Tool
Do NOT use this tool when:
1. You are listing tasks or tracking progress (use the todo tool instead)
2. You haven't yet reached any valuable or strategic information
3. You are simply answering a question

## Important Guidelines
- Record only high-value, decision-level, conclusion-related information
- Do not restate the entire conversation
- Focus on what must be remembered for correct future behavior
- Avoid duplicating todo content
"""

READ_MEMORY_PROMPT = """
Read one or more memory(s) content

## Args
- title (str | list[str]): Titles of memories in the `## Available Memories` section to be read

## Returns
- str: Memory content with date

## Note
- Use this tool to retrieve previously recorded strategic decisions, observations, conclusions or other information for the current work session
- This tool helps you recall important past information and maintain consistency

## When to Use This Tool
Use this tool in these scenarios:
1. Before making a decision that may conflict with previously recorded conclusions
2. When you need to verify existing constraints, rules, or policies
3. When a choice depends on previously established observations or conclusions
4. When you suspect a similar decision has already been made and should not be re-derived
5. When correctness depends on aligning with prior decisions or tool result summaries

## When NOT to Use This Tool
Do NOT use this tool when:
1. The current step is independent and does not rely on prior decisions
2. You are simply answering a question that does not depend on past decisions
3. You have just written the memo and already remember its content
4. You are trying to retrieve general conversation history

## Important Guidelines
- Do not use it as a substitute for conversation history or planning context
- Avoid unnecessary reads, only use it when prior information affect correctness
"""



REQUEST_USER_INPUT_PROMPT = """
Request one or more answers, confirmations, selections, or decisions directly from the user.
When starting a project and requirements materially affect implementation, use this tool to show
an interactive question card above the chat composer. Group 1–3 concise questions per call.
Offer 2–3 useful choices with the recommended choice first and marked (推荐); free text is always supported.
Extra comments are optional. Mark open-ended supplementary questions optional=true; never require an extra comment after an option is selected.
Do not invent answers or silently choose an option while this tool is waiting. Continue the original task after the answer.
Windows will notify the user automatically; no additional notification tool is needed.

## Args
- questions (list[Question]): List of questions to send to the user
    Each question item must contain:
    - question (str): The question shown to the user. Must not be empty
    - options (list[str]): Optional predefined selectable options for the user
        Use an empty list if free-form input is expected.
    - multiselection (bool): Whether the user is allowed to select multiple options from the list
        If `True`, multiple choices are permitted; if `False`, only a single choice is allowed

## Returns
- str | None:
    - Returns the user's response if received successfully
    - Returns None if the user is unavailable, refuses to answer, disconnects, or the request is cancelled

## Note
- Users usually do not want to be interrupted unless necessary
- This tool blocks execution until:
    - the user provides a response
    - the request is cancelled
    - or the interaction ends without a result
- This tool sends interactive questions to the user and blocks execution while waiting for a response
- The tool resumes automatically after a user response or cancellation
- Options are suggestions for user selection, not strict limitations on user responses
- Multiple related questions can be grouped into a single tool call

## When to Use This Tool
Use this tool in these scenarios:
1. When required information is missing
2. When the user must make a decision between multiple valid choices
3. When confirmation or approval is required before continuing
4. When execution depends on user preferences or configuration choices
5. When tool results are ambiguous and require user interpretation
6. When the current task cannot continue reliably without user input
7. When you want to display a confirmation dialog to the user before performing an operation

## When NOT to Use This Tool
Do NOT use this tool when:
1. You already have enough information to continue
2. The answer can be reasonably inferred from existing context
3. You are asking unnecessary confirmations for obvious next actions
4. The missing information does not block meaningful progress
5. The question is low-value, vague, or overly broad
6. You can continue execution first and ask later only if needed

## Important Guidelines
- Prefer batching related questions into a single tool call instead of sending multiple separate requests
- Keep each question short, specific, and actionable
- Ask only for information that is truly necessary
- Avoid asking duplicate questions already answered in memory or conversation context
- Provide options when they improve clarity or reduce user effort
- Use empty options for open-ended questions
- Do not assume the user will select one of the provided options exactly
- Always handle the possibility that the tool may return None
- If the user does not respond, decide whether to continue with fallback behavior or stop execution safely
"""



# Command
RUN_WORKSPACE_COMMAND_PROMPT = """
Execute a PowerShell command in the user's selected local workspace

## Args
- command (str): The shell command to execute
    
## Returns
- str: The command output, or an error message if execution fails

## Note
- Command output will be truncated if exceeds a string length limit
- If the output is truncated, a `[output truncated]` marker will appear in the result

## When to Use This Tool
Use this tool in these scenarios:
1. When you need to run programs, scripts, or development tools inside the workspace
2. When you need to execute CLI utilities (e.g., build tools, package managers, linters)
3. When you need to inspect the workspace environment (e.g., list files, check system information)
4. When a task requires executing commands that cannot be completed by other available tools

## When NOT to Use This Tool
Do NOT use this tool when:
1. The task involves reading, creating, modifying, or deleting files (dedicated file tools should be used instead)
2. The command is unrelated to the workspace task
3. The task can be completed directly through reasoning without executing a command

## Important Guidelines
- Ensure the command operates within the selected workspace directory
- Prefer safe and deterministic commands
- Avoid destructive commands unless explicitly required by the task
- Carefully check command syntax before execution
"""



# Run code
RUN_PYTHON_CODE_PROMPT = """
Execute Python code immediately in the selected local workspace

## Args
- code (str): Python code as a string
- run_args (list[str]): Optional command-line arguments passed to the script

## Returns
- str: Command output including stdout or error messages

## Note
- This tool runs Python code as a temporary script
- The code is executed once and is NOT saved as a persistent workspace file
- Code output will be truncated if exceeds a string length limit
- If the output is truncated, a `[output truncated]` marker will appear in the result

## When to Use This Tool
Use this tool in these scenarios:
1. When a task requires quick computation or data processing
2. When temporary Python code needs to be executed immediately
3. When performing one-off analysis, transformations, or calculations
4. When the code does not need to persist after execution
5. When you want to wait for something to finish, using asyncio.sleep()

## When NOT to Use This Tool
Do NOT use this tool when:
1. The Python program needs to be modified or reused later
2. The code should be saved as part of the workspace
3. The task requires iterative development or repeated execution of the same script

## Important Guidelines
- Code executed by this tool is ephemeral and will not be kept as a normal workspace source file
- If the program should persist in the workspace, write it to a file first
- Ensure required input files exist before execution
- Return outputs that help progress the task
"""



# Search
SEARCH_KNOWLEDGE_BASE_PROMPT = """
Retrieve relevant document chunks from the knowledge base based on one query sentence and return the matched text snippets together with their source information

## Args
- query (str): One retrieval query sentence used to search the knowledge base
- document_ids (list[str]): The IDs of the target documents to retrieve

## Returns
- str: A string containing relevant document chunks and their source metadata

## Note
- This tool performs knowledge base retrieval only and does NOT fetch information on internet

## When to Use This Tool
Use this tool in these scenarios:
1. When the user asks questions that may be answered from the internal knowledge base
2. When you need supporting document snippets before answering
3. When you want grounded evidence with source attribution
4. When you need to search across one or more queries for relevant knowledge

## When NOT to Use This Tool
Do NOT use this tool when:
1. The question can be answered reliably without knowledge base retrieval
2. The user only wants a generic response with no need for grounding
3. The task requires full-document reading rather than snippet-level retrieval
4. The relevant content has already been provided directly in the conversation

## Important Guidelines
- The results returned by this tool are retrieved document chunks, not full documents
- Each chunk should include or be associated with its source information
- Do NOT assume missing context beyond the retrieved snippets
- If more context is required, use a follow-up tool or workflow to read the full source document
- Never fabricate retrieved content or source references
"""

SEARCH_WEB_BY_KEYWORDS_PROMPT = """
Search the web for pages related to given keyword(s) and return a list of results containing the page title, URL, and a short description snippet.

## Args
- key_word (str | list[str]): One or more search keywords.

### Keyword Usage
- If `key_word` is a string, it is used directly as the search query.
- If `key_word` is a `list[str]`, all keywords are treated as parts of the same search intent and will be combined into a single search query.
- Keywords in the list should be semantically related and describe the same target, concept, entity, or topic.

## Returns
- str: A string containing formatted webpage results and optional image results

## Note
- This tool only provides search results (metadata)
- This tool does NOT retrieve the full content of webpages
- The search results may contain images

## Examples:
- `["OpenStarry", "Agent"]` → searches for `"OpenStarry Agent"` because the intent is to find an Agent named OpenStarry.
- `["python", "asyncio"]` → searches for `"python asyncio"` because the keywords describe a related topic.
- `["OpenAI", "GPT-5"]` → searches for `"OpenAI GPT-5"` because the keywords belong to the same subject.

Avoid using a list when keywords represent unrelated search intents:
- Bad: `["weather", "Tesla"]`
- Bad: `["pizza", "quantum computing"]`

For unrelated topics, perform separate searches instead of combining them into a single keyword list.

## When to Use This Tool
Use this tool in these scenarios:
1. When the user explicitly asks to search for information on the internet
2. When the task requires up-to-date or external information not in your knowledge
3. When you need to discover relevant webpages before reading their content
4. When you want to get some images from internet

## When NOT to Use This Tool
Do NOT use this tool when:
1. The question can be answered using existing knowledge
2. The user already provided specific URLs
3. The task requires reading webpage content by url directly

## Important Guidelines
- The results returned by this tool are only summaries
- The images returned by this tool include metadata such as image URLs
- Do NOT assume the full content of a webpage based on the title or description
- If detailed information is required, call `search_web_by_urls` with the returned URLs
- Never fabricate search results or URLs
"""

SEARCH_WEB_BY_URLS_PROMPT = """
Fetch and extract the main readable content from one or more webpages

## Args
- urls (str | list[str]): One or more webpage URLs

## Returns
- str: Extracted textual content from each webpage

## Note
- The search results are not contain image or any binary data
- This tool retrieves and processes webpage content from the provided URLs
- It extracts the primary textual content of the page for analysis

## When to Use This Tool
Use this tool in these scenarios:
1. When the user asks to analyze or summarize specific webpages
2. When `search_web_by_keywords` returned relevant URLs and you need their full content
3. When detailed webpage information is required beyond titles and descriptions

## When NOT to Use This Tool
Do NOT use this tool when:
1. You do not have a valid URL
2. You only need webpage titles or search results descriptions
3. The task does not require reading webpage content

## Important Guidelines
- Only fetch URLs provided by the user or returned from `search_web_by_keywords`
- Never fabricate or guess webpage content
- Avoid fetching unnecessary webpages
"""
