# Global configuration settings for the OpenStarry Agent Core module.
VERSION = "2.2.2"

import os
import uuid
import platform

OPERATION_SYSTEM = platform.system().lower()

DEBUG = True
TRACE = True
MAX_LOG_FILE_SIZE = 5 * 1024 * 1024

OUTPUT_GRAPH_PNG = False  # Whether to output the agent graph as a PNG file

BASE_DIR = os.environ.get("AGENT_BASE_DIR", "../OpenStarry_running_time/") # Download cache dir

SANDBOX_DOCKER_IMAGE_NAME = "agent-sandbox:latest" # Sandbox image name.

TOOLS_MAX_OUTPUT_LENGTH = 32000

BASE_URL = {       # Base URL for the LLM service
    # Ollama
    'ollama:local': 'http://localhost:11434',  # Local
    'ollama': 'https://ollama.com',  # Cloud
    
    # OpenAI
    'openai': 'https://api.openai.com/v1',
    
    # Google (Gemini)
    'google': 'https://generativelanguage.googleapis.com',
    
    # Qwen (通义千问)
    'qwen': 'https://dashscope.aliyuncs.com/v1',
    
    # Qianfan (百度千帆)
    'qianfan': 'https://qianfan.baidubce.com/v1',
    
    # DeepSeek
    'deepseek': 'https://api.deepseek.com/v1',

    # Moonshot (月之暗面)
    'moonshot': 'https://api.moonshot.cn/v1',

    # XiaomiMIMO
    'xiaomimimo': 'https://api.xiaomimimo.com/v1',
}  


MAX_RETRY = 8 # Max retry when llm_call failure, make sure it great than 3

TASK_SERVER_BASE_URL = os.environ.get("TASK_SERVER_BASE_URL", "http://localhost:5090")

AGENT_SERVICE_URL = os.environ.get("AGENT_SERVICE_URL", "http://localhost:5091")  # OpenStarry service URL

MEMORY_SERVICE_BASE_URL = os.environ.get("MEMORY_SERVICE_BASE_URL", "http://localhost:5093")

FILE_SERVICE_URL = os.environ.get("FILE_SERVICE_URL", "http://localhost:5094")

PUBLIC_FILE_ADRESS = "" # Files generated by agent will upload at this internet adress

AGENT_SERVICE_ID = str(uuid.uuid4().hex)

LOAD_FORIGN_TOOL = False

GENERATION_TTL = 600  # Clear those finished and aborted generation ctx, seconds
CONTIANER_TTL = 6000
GRAPH_CACHE_TTL = 600
CACHE_CLEAN_INTERVAL = 300

_ORIGINAL_PROXY_ENV = {
    "HTTP_PROXY": os.environ.get("HTTP_PROXY"),
    "HTTPS_PROXY": os.environ.get("HTTPS_PROXY"),
    "NO_PROXY": os.environ.get("NO_PROXY"),
}

# Make sure local inter-service traffic never goes through an external proxy.
_LOCAL_NO_PROXY = "localhost,127.0.0.1,::1"
_existing_no_proxy = os.environ.get("NO_PROXY", "")
os.environ["NO_PROXY"] = ",".join(
    part for part in (_existing_no_proxy + "," + _LOCAL_NO_PROXY).split(",") if part.strip()
)
