import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
const browser = await chromium.connectOverCDP('http://127.0.0.1:9230')
const page = browser.contexts()[0].pages().find(page => page.url().includes('index.html'))
if (!page) throw Error('Desktop page missing')
const errors = []; page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') console.error(message.text().slice(0, 180)) })
await page.evaluate(() => { location.hash = '/idePage' })
await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
await page.getByRole('dialog').getByLabel('回答或补充说明').fill('桌面 IDE QA')
await page.getByRole('dialog').getByRole('button', { name: '提交回答' }).click()
await expect(page.locator('.cm-content')).toContainText('Hello, OpenStarry!')
await page.locator('.cm-content').fill('console.log("DESKTOP_OK");\n')
await expect(page.locator('.os-tab.active')).toContainText('●')
await page.getByRole('button', { name: '保存', exact: true }).click()
await page.getByLabel('运行命令', { exact: true }).fill('main.js'); await page.getByRole('button', { name: '▶ 运行', exact: true }).click()
await expect(page.getByLabel('运行输出')).toContainText('DESKTOP_OK', { timeout: 15000 })
await expect(page.getByLabel('运行输出')).toContainText('退出码 0')
await page.getByRole('navigation', { name: 'IDE 面板' }).getByRole('button', { name: '代码', exact: true }).click()
await page.locator('.cm-content').fill('console.log("DESKTOP_CHANGED");\n')
await page.getByRole('navigation', { name: 'IDE 面板' }).getByRole('button', { name: '审查', exact: true }).click()
await expect(page.locator('.cm-deletedChunk')).toContainText('DESKTOP_OK')
await page.screenshot({ path: '../../tmp/ide-20260919/desktop.png' })
await page.getByRole('button', { name: '保存修改', exact: true }).click()
await page.getByRole('button', { name: '新建文件', exact: true }).click()
await page.getByRole('dialog').getByLabel('回答或补充说明').fill('index.html')
await page.getByRole('dialog').getByRole('button', { name: '提交回答' }).click()
await expect(page.locator('.os-breadcrumb')).toContainText('index.html')
await page.locator('.cm-content').fill('<h1>Desktop preview works</h1><script>document.body.dataset.ready="yes";try{parent.document.body.dataset.leak="bad"}catch{document.body.dataset.isolated="yes"}</script>')
await page.getByRole('button', { name: '保存', exact: true }).click()
await page.getByRole('button', { name: '网页预览', exact: true }).click()
await expect(page.frameLocator('.os-preview').getByRole('heading', { name: 'Desktop preview works' })).toBeVisible({ timeout: 15000 })
await expect(page.frameLocator('.os-preview').locator('body')).toHaveAttribute('data-ready', 'yes')
await expect(page.frameLocator('.os-preview').locator('body')).toHaveAttribute('data-isolated', 'yes')
await page.getByRole('button', { name: '打开文件 main.js', exact: true }).click()
await page.evaluate(() => { location.hash = '/settingPage' })
await page.getByRole('heading', { name: 'Agent 调用与 IDE' }).waitFor()
await page.getByRole('switch', { name: '启用工具调用', exact: true }).check()
await page.getByRole('button', { name: '保存 Agent 设置' }).click()
await page.evaluate(() => {
  localStorage.setItem('modelProvider', 'custom'); localStorage.setItem('modelName', 'second-model')
  return window.api.createLlmProvider('local-user', { provider_name: 'IDE QA', endpoint: 'http://127.0.0.1:8766/v1', type: 'openai', model_list: ['fixture-model', 'second-model'], description: '' }).then(async () => {
    const providers = await window.api.getLlmProviders('local-user'); const provider = providers.find(item => item.provider_name === 'IDE QA')
    if (!provider) throw Error('Provider not created')
    localStorage.setItem('activeProvider', JSON.stringify({ provider_id: provider.provider_id, name: 'IDE QA', api_key: '' }))
    await window.api.system.sharedPreferences({ modelProvider: 'custom', modelName: 'second-model', activeProvider: { provider_id: provider.provider_id, name: 'IDE QA' } })
  })
})
await page.reload(); await page.waitForFunction(async () => (await window.api.system.runtimeStatus()).phase === 'ready')
await page.locator('[data-route="/assistPage"]').click()
await page.getByText('second-model', { exact: true }).first().waitFor({ timeout: 15000 })
assert.equal(await page.evaluate(() => localStorage.getItem('modelName')), 'second-model')
await page.locator('[data-route="/idePage"]').click()
await expect(page.locator('.cm-content')).toContainText('DESKTOP_CHANGED')
assert.deepEqual(errors, [])
console.log('Desktop Electron IDE passed: CSP sandbox execution, diff, persistence, tool settings, saved model selection')
await browser.close()
