server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /sw.js {
    add_header Cache-Control "no-cache";
  }
  location = /asset-manifest.json {
    add_header Cache-Control "no-cache";
  }
  location = /index.html {
    add_header Cache-Control "no-cache";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|webmanifest)$ {
    expires 7d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}
